### ISSUE TITLE
Economy discount type to allow X IN-USE protections

### ISSUE THREAD

**Issue by Hidendra** [Hidendra/LWC#109]
```
discount:
    active: false
    type: XXXX (name undecided)
    amount: 5
    newCharge: 0.00
```
- They get 5 protections for free
- Every protection after this costs regular price
- If they remove one of the protections they got for free, their next protection is free.
