### ISSUE TITLE
[Suggestions] Notice and protection

### ISSUE THREAD

**Issue by luis-guideti** [Hidendra/LWC#172]
Here ya go some suggestions i have C:

Something to disable the Created a private chest successfully, or put he ''per block''
like this

```
blocks:
    chest:
        enabled: true
        autoRegister: private
        DisplayMsg: true
    stone:
        enabled: true
        autoRegister: private
        DisplayMsg: false
```

if DisplayMsg = false, Do not will show the "Create a private..." and "Notice: That block..."
## 

Protection radius, like in the doors, but with all other blocks around!

Something like this, i place a block in the floor, and all the sides of this block will be protected with 1 block radius.
at least the griffers will be incapable of put blocks inside your house.

Sorry about the bad english C: it's not my main language.
