### ISSUE TITLE
Limits not working right it seems

### ISSUE THREAD

**Issue by ghost** [Hidendra/LWC#505]
I'm not getting any errors reported by the server but my players are exceeding their max allotted protections without even setting any. I use GroupManager for permissions and, as an example, I'll use this one player's specific groups.

In limitsv2.yml I have:

```
Default:
    chest: 1
    door: 1
Builder:
    chest: 1
    door: 1
VIP:
    chest: 3
    door: 1
```

In the groups that the users belong to:

default:
- lwc.protect

builder: has no lwc specific permissions

vip: has no lwc specific permissions

I have not seen any reported errors like this recently so I'm guessing I'm the only one with the problems. The specific user's primary group is Builder with a sub-group VIP.
