### ISSUE TITLE
Autoclose, Flag, Doors on LWC 4.3.1. And actual dev-Builds

### ISSUE THREAD

**Issue by Jobsti** [Hidendra/LWC#515]
**Heyho Hidendra**
Since a few weeks, the dev-builds doesn't work, why?
(deleted my sever.log, but I remember something like _"(is it up to date?) can't find java lib ...."_ )

LWC 4.3.1 works without any problems with #2606, except **Autoclose**.

```
doors:
    enabled: true
    doubleDoors: true
    action: openAndClose
    interval: 3
```

Autoclose works (on DoubleDoors too), with toggle and also with openAndClose. (Should only work with openAndClose?!)
Also works, if Flag Autoclose is on or off! (The flag does nothing...)

If _enabled: false_, double-doors and AutoClose doesn't work. (also not the ingame-Flag)

I don't want to open Iron Doors on click, but I want to use the Autoclose flag ingame for autoclose some doors.
doubleDoors isn't important, but would be nice.

Bug found: See next Post.
