### ISSUE TITLE
Regression ( Issue #133 ) Protect block that a protected object is attached to.

### ISSUE THREAD

**Issue by shinji257** [Hidendra/LWC#685]
For Issue #133 there was an update that caused LWC to automatically protect the block that a protected button or lever was attached to.  It seems with the current version it is broken and I can now break the block they are attached to causing the button or lever to drop and bypass the protection.  Can we fix this?

P.S. - I noted codes changes for signs and trap doors but none for buttons/levers... Looks like the face changes happened here too?

EDIT: Please add WOOD_BUTTON to that as well.  I only see STONE_BUTTON and LEVER in the code...

```
    lever:
        enabled: true
    wood_button:
        enabled: true
    stone_button:
        enabled: true
```
