### ISSUE TITLE
Bug: Pressure plates can open doors ignoring access list

### ISSUE THREAD

**Issue by shinji257** [Hidendra/LWC#707]
If I have the redstone flag disabled (denyRedstone: false in config) on a private door then pressure plates will allow anyone to enter the door bypassing the access list for the door itself.  If I set the redstone flag on then no one can enter using a pressure plate (placed after the flag is set) including the owner of the door.

Note: stone_plate and wood_plate are added to allow individual protection beyond a door and I have a separate ticket about that scenario.  Doesn't affect the redstone flag/door issue.

Am I doing something wrong?

Config:

```
core:
    locale: en
    flushInterval: 10
    cacheSize: 10000
    precache: -1
    showNotices: true
    showMyNotices: false
    opIsLWCAdmin: true
    disableHistory: false
    townyBorders: false
    groupPrefix: group.
    updateNotifier: true
optional:
    onlyProtectWhenOwnerIsOnline: false
    onlyProtectWhenOwnerIsOffline: false
    exemptBlocks: []
    optOut: false
    blacklistedBlocks:
    - '166'
    - '154'
    blacklistedPlayers:
    - plr
    useProtectionLimits: true
database:
    adapter: sqlite
    path: plugins/LWC/lwc.db
    host: localhost
    database: lwc
    username: ''
    password: ''
    prefix: lwc_
    ping_interval: 300
protections:
    denyRedstone: false
    denyHoppers: true
    autoRegister: false
    ignoreBlockDestruction: false
    ignoreLeftClick: false
    ignoreRightClick: false
    ignoreExplosions: false
    allowEntityBreakDoor: false
    allowEntityInteract: false
    quiet: false
    readonly-modify: false
    readonly-remove: false
    blocks:
        chest:
            enabled: true
            autoRegister: private
        furnace:
            enabled: true
            autoRegister: private
        dispenser:
            enabled: true
            autoRegister: private
        sign:
            enabled: true
            autoRegister: private
        wooden_door:
            enabled: true
        iron_door:
            enabled: true
        trap_door:
            enabled: true
        fence_gate:
            enabled: true
        trapped_chest:
            autoRegister: private
            enabled: true
        lever:
            enabled: true
        wood_button:
            enabled: true
        stone_button:
            enabled: true
        hopper:
            enabled: true
        brewing_stand:
            enabled: true
        stone_plate:
            enabled: true
        wood_plate:
            enabled: true
modes:
    droptransfer:
        enabled: true
        crossWorld: false
    persist:
        enabled: true
```
